// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "autoPutDown.h"
float putDownSpeed=0;
autoPutDown::autoPutDown(int timeOut, float sp) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::liftMechanism);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	putDownSpeed=sp;
	SetTimeout(timeOut);
}

// Called just before this Command runs the first time
void autoPutDown::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void autoPutDown::Execute() {
	if (Robot::liftMechanism->lowerLimit->Get()) {
		Robot::liftMechanism->liftMotor->Set(putDownSpeed);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool autoPutDown::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void autoPutDown::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void autoPutDown::Interrupted() {

}
